name = "OpenPMDBeamphysics"
uuid = "f85cbb92-938a-4877-a34b-92f8b55ab56a"
authors = ["ndwang <ndwang3@gmail.com>"]
version = "0.1.0"

[deps]
AtomicAndPhysicalConstants = "5c0d271c-5419-4163-b387-496237733d8b"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
julia = "1.10"
HDF5 = "0.17"
Plots = "1.40"
StatsBase = "0.34"
Unitful = "1.22"
